In [1]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('./WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [5]:
df.dropna(inplace=True, axis=1)

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
Churn               0
dtype: int64

In [7]:
# let's encode the column calling the encoding function created in utils.py file

from util import encode_categorical_columns

# List of columns to encode
columns_to_encode = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                     'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
                     'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

# Call the function to encode categorical columns
df_en = encode_categorical_columns(df, columns_to_encode)

In [8]:
# Replace 'Yes' with 1 and 'No' with 0 in the 'Churn' column
df_en['Churn'].replace({'Yes': 1, 'No': 0}, inplace=True)

In [9]:
df_en

,customerID,tenure,MonthlyCharges,Churn,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No,...,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,29.85,0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,5575-GNVDE,34,56.95,0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3668-QPYBK,2,53.85,1,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,7795-CFOCW,45,42.30,0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,9237-HQITU,2,70.70,1,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,84.80,0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
7039,2234-XADUH,72,103.20,0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
7040,4801-JZAZL,11,29.60,0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7041,8361-LTMKD,4,74.40,1,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7042,3186-AJIEK,66,105.65,0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0

In [10]:
# Separate target and features
X = df_en.drop(columns=['customerID', 'Churn'])
y = df_en['Churn']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5634, 39)
X_test shape: (1409, 39)
y_train shape: (5634,)
y_test shape: (1409,)

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 39 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   tenure                                   7043 non-null   int64
 1   MonthlyCharges                           7043 non-null   float64
 2   gender_Male                              7043 non-null   float64
 3   SeniorCitizen_1                          7043 non-null   float64
 4   Partner_Yes                              7043 non-null   float64
 5   Dependents_Yes                           7043 non-null   float64
 6   PhoneService_Yes                         7043 non-null   float64
 7   MultipleLines_No                         7043 non-null   float64
 8   MultipleLines_No phone service           7043 non-null   float64
 9   MultipleLines_Yes                        7043 non-null   float64
 10  InternetService_DSL                      7043 non-null   float64
 11  InternetService_Fiber optic              7043 non-null   float64
 12  InternetService_No                       7043 non-null   float64
 13  OnlineSecurity_No                        7043 non-null   float64
 14  OnlineSecurity_No internet service       7043 non-null   float64
 15  OnlineSecurity_Yes                       7043 non-null   float64
 16  OnlineBackup_No                          7043 non-null   float64
 17  OnlineBackup_No internet service         7043 non-null   float64
 18  OnlineBackup_Yes                         7043 non-null   float64
 19  DeviceProtection_No                      7043 non-null   float64
 20  DeviceProtection_No internet service     7043 non-null   float64
 21  DeviceProtection_Yes                     7043 non-null   float64
 22  TechSupport_No                           7043 non-null   float64
 23  TechSupport_No internet service          7043 non-null   float64
 24  TechSupport_Yes                          7043 non-null   float64
 25  StreamingTV_No                           7043 non-null   float64
 26  StreamingTV_No internet service          7043 non-null   float64
 27  StreamingTV_Yes                          7043 non-null   float64
 28  StreamingMovies_No                       7043 non-null   float64
 29  StreamingMovies_No internet service      7043 non-null   float64
 30  StreamingMovies_Yes                      7043 non-null   float64
 31  Contract_Month-to-month                  7043 non-null   float64
 32  Contract_One year                        7043 non-null   float64
 33  Contract_Two year                        7043 non-null   float64
 34  PaperlessBilling_Yes                     7043 non-null   float64
 35  PaymentMethod_Bank transfer (automatic)  7043 non-null   float64
 36  PaymentMethod_Credit card (automatic)    7043 non-null   float64
 37  PaymentMethod_Electronic check           7043 non-null   float64
 38  PaymentMethod_Mailed check               7043 non-null   float64
dtypes: float64(38), int64(1)
memory usage: 2.1 MB

In [13]:
# Create a pipeline for Logistic Regression
logistic_regression_pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Standardize features (optional)
    ('classifier', LogisticRegression())
])

# Create a pipeline for Random Forest Classifier
random_forest_pipeline = Pipeline([
    ('classifier', RandomForestClassifier())
])

In [14]:
# Fit the pipelines on the training data
logistic_regression_pipeline.fit(X_train, y_train)
random_forest_pipeline.fit(X_train, y_train)

# Evaluate the pipelines on the testing data
logistic_regression_accuracy = logistic_regression_pipeline.score(X_test, y_test)
random_forest_accuracy = random_forest_pipeline.score(X_test, y_test)

print("Logistic Regression Accuracy:", logistic_regression_accuracy)
print("Random Forest Accuracy:", random_forest_accuracy)

Logistic Regression Accuracy: 0.8197303051809794
Random Forest Accuracy: 0.7934705464868701